# Generated by Django 5.0 on 2024-02-02 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'designer_table',
            },
        ),
        migrations.CreateModel(
            name='FlowerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('star_given', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'review_table',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_flower', models.ImageField(default='flower_image/flower_default_image.jpg', upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('symbolism', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'flower_table',
            },
        ),
        migrations.CreateModel(
            name='FlowerDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.designer')),
            ],
            options={
                'db_table': 'flower_designer_table',
            },
        ),
    ]
